version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "9091:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - "mongodb"

  web-page:
    container_name: webpage
    #image: enrogaj/web-game-repo:finalweb
    build: ./WebPage
    ports:
      - "9090:8079"
    depends_on:
      - "mongodb"
      - "mongo-express"

  spring-server:
    container_name: springserver
    #image: enrogaj/web-game-repo:finalweb
    build: ./SpringServer
    ports:
      - "9089:8080"
    depends_on:
      - "mongodb"
      - "mongo-express"

volumes:
  data: {}

networks:
  default:
    name: my-first-app-network
